# Generated by Django 5.1.2 on 2024-11-02 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_remove_forum_preface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum_reply',
            name='reply_to',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.forum_reply'),
        ),
    ]
