# Generated by Django 5.1.2 on 2024-11-02 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_thought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suvichar', models.CharField(max_length=300)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
