# Generated by Django 5.1.2 on 2024-11-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_thought',
            name='author',
            field=models.CharField(default='Anonymous', max_length=300),
        ),
        migrations.AddField(
            model_name='daily_thought',
            name='used',
            field=models.IntegerField(default=0),
        ),
    ]
