# Generated by Django 5.1.2 on 2024-11-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_used_daily_thought_used_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_thought',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
