# Generated by Django 5.1.2 on 2024-11-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_daily_thought_last_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_thought',
            name='last_used',
            field=models.DateField(blank=True, null=True),
        ),
    ]
